"""empty message

Revision ID: 015b757581ef
Revises: 2c85523b96c3
Create Date: 2025-05-19 17:49:24.737221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015b757581ef'
down_revision = '2c85523b96c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=1000), nullable=False, server_default='سبد خرید'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
