"""empty message

Revision ID: a1616cfcdf4d
Revises: c6ff22439ebd
Create Date: 2025-05-12 22:51:39.400574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1616cfcdf4d'
down_revision = 'c6ff22439ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_baskets')
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.alter_column('crested_at',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.alter_column('crested_at',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    op.create_table('_alembic_tmp_baskets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('descrption', sa.TEXT(), nullable=True),
    sa.Column('crested_at', sa.VARCHAR(length=200), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
